@CampoMarketApi_HostAddress = http://localhost:5079
@token = pega_aqui_el_access_token

POST {{CampoMarketApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@campomarket.test",
  "password": "Admin123!"
}

###

GET {{CampoMarketApi_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

###

GET {{CampoMarketApi_HostAddress}}/api/auth/admin-check
Authorization: Bearer {{token}}
